"""Template seed data — 143 named audit tests built on 35 base detectors.

Each row: (code, name, detector_name, default_params, subledger, category, weight, tags, description)
"""

UNIVERSAL = [
    ("U01", "Missing Values in Required Fields", "null_check",
     {"required_fields": []}, None, "DATA_QUALITY", 0.8, ["quality"],
     "Flag records with NULL or blank values in required fields"),
    ("U02", "Invalid Date Formats", "type_validation",
     {"field": "date", "expected_type": "date"}, None, "DATA_QUALITY", 0.7, ["quality"],
     "Flag records where a date field fails to parse"),
    ("U03", "Invalid Numeric Values", "type_validation",
     {"field": "amount", "expected_type": "numeric"}, None, "DATA_QUALITY", 0.7, ["quality"],
     "Flag records where a numeric field fails to parse"),
    ("U04", "Email Format Validation", "format_validation",
     {"field": "email", "pattern": "email"}, None, "DATA_QUALITY", 0.5, ["quality", "format"],
     "Flag improperly formatted email addresses"),
    ("U05", "Phone Format Validation", "format_validation",
     {"field": "phone", "pattern": "phone"}, None, "DATA_QUALITY", 0.5, ["quality", "format"],
     "Flag improperly formatted phone numbers"),
    ("U06", "IBAN Format Validation", "format_validation",
     {"field": "iban", "pattern": "iban"}, None, "DATA_QUALITY", 0.6, ["quality", "format"],
     "Flag improperly formatted IBAN values"),
    ("U07", "Tax ID (UAE TRN) Validation", "format_validation",
     {"field": "trn", "pattern": "uae_trn"}, None, "DATA_QUALITY", 0.6, ["quality", "format"],
     "Flag invalid 15-digit UAE Tax Registration Numbers"),
    ("U08", "Blank Rows Detection", "blank_rows",
     {}, None, "DATA_QUALITY", 0.5, ["quality"],
     "Detect entirely blank or header-only rows"),
    ("U09", "Out-of-Range Values", "range_validation",
     {"field": "amount", "min": 0, "max": None}, None, "DATA_QUALITY", 0.7, ["quality"],
     "Flag numeric values outside expected range"),
    ("U10", "Descriptive Statistics", "statistics",
     {"numeric_fields": []}, None, "ANALYTICAL", 0.2, ["stats"],
     "Compute descriptive stats (sum, mean, stddev, min, max, quartiles) per numeric field"),
    ("U11", "Benford 1st Digit", "benford",
     {"numeric_field": "amount", "digit_mode": "first"}, None, "FRAUD", 0.5, ["benford", "fraud"],
     "Benford's Law analysis on first digit"),
    ("U12", "Benford 1st Two Digits", "benford",
     {"numeric_field": "amount", "digit_mode": "first_two"}, None, "FRAUD", 0.6, ["benford", "fraud"],
     "Benford's Law analysis on first two digits (more sensitive)"),
    ("U13", "Benford Last Two Digits", "benford",
     {"numeric_field": "amount", "digit_mode": "last_two"}, None, "FRAUD", 0.6, ["benford", "fraud"],
     "Benford's Law analysis on last two digits (detects rounding/invention)"),
    ("U14", "Benford 2nd Digit", "benford",
     {"numeric_field": "amount", "digit_mode": "second"}, None, "FRAUD", 0.5, ["benford", "fraud"],
     "Benford's Law analysis on second digit"),
    ("U15", "Referential Integrity Check", "referential_integrity",
     {"child_field": "ref_id", "parent_values": []}, None, "DATA_QUALITY", 0.9, ["quality", "integrity"],
     "Flag records where FK value doesn't exist in parent dataset"),
]

AP = [
    ("AP01", "Duplicate Invoice Numbers (same vendor)", "duplicates",
     {"key_fields": ["vendor_id", "invoice_no"]}, "ACCOUNTS_PAYABLE", "FRAUD", 1.2,
     ["ap", "duplicate"], "Same invoice_no for same vendor — likely double entry"),
    ("AP02", "Duplicate Invoice Numbers (any vendor)", "duplicates",
     {"key_fields": ["invoice_no"]}, "ACCOUNTS_PAYABLE", "FRAUD", 0.9,
     ["ap", "duplicate"], "Invoice_no shared across vendors"),
    ("AP03", "Duplicate Payments", "duplicates",
     {"key_fields": ["vendor_id", "amount"]}, "ACCOUNTS_PAYABLE", "FRAUD", 1.3,
     ["ap", "duplicate", "payment"], "Same vendor + amount — likely duplicate payment"),
    ("AP04", "Same Invoice Different Vendor", "same_same_different",
     {"same_fields": ["invoice_no"], "different_field": "vendor_id"},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.2, ["ap", "fraud"],
     "Identical invoice number attributed to different vendors"),
    ("AP05", "Same Vendor Same Amount Different Invoice", "same_same_different",
     {"same_fields": ["vendor_id", "amount"], "different_field": "invoice_no"},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.0, ["ap", "duplicate"],
     "Repeat billing pattern: same vendor + amount under different invoice numbers"),
    ("AP06", "Fuzzy Duplicate Vendor Names", "fuzzy_dup",
     {"field": "vendor_name", "threshold": 85}, "ACCOUNTS_PAYABLE", "FRAUD", 0.8,
     ["ap", "vendor", "fuzzy"], "Near-duplicate vendor master records"),
    ("AP07", "Invoice Gaps by Vendor", "gaps",
     {"key_field": "invoice_no", "group_by": "vendor_id"},
     "ACCOUNTS_PAYABLE", "ANALYTICAL", 0.5, ["ap", "sequence"],
     "Missing invoice numbers in per-vendor sequence"),
    ("AP08", "AP Payment on Weekend", "weekend_transactions",
     {"date_field": "payment_date", "include_holidays": False},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.0, ["ap", "temporal"],
     "Payments posted Fri/Sat"),
    ("AP09", "AP Payment on UAE Holiday", "weekend_transactions",
     {"date_field": "payment_date", "include_holidays": True, "holidays_ref": "uae"},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.1, ["ap", "temporal"],
     "Payments posted on UAE public holidays"),
    ("AP10", "Payment After Business Hours", "after_hours",
     {"datetime_field": "payment_datetime", "business_start": "08:00", "business_end": "18:00"},
     "ACCOUNTS_PAYABLE", "FRAUD", 0.8, ["ap", "temporal"],
     "Payment activity outside 08:00–18:00"),
    ("AP11", "Round-Dollar Payments", "round_number",
     {"amount_field": "amount", "round_pattern": "000"},
     "ACCOUNTS_PAYABLE", "FRAUD", 0.4, ["ap", "round"],
     "Payments ending in 000"),
    ("AP12", "Very Round Payments (0000)", "round_number",
     {"amount_field": "amount", "round_pattern": "0000"},
     "ACCOUNTS_PAYABLE", "FRAUD", 0.6, ["ap", "round"],
     "Payments ending in 0000"),
    ("AP13", "Benford on Invoice Amounts", "benford",
     {"numeric_field": "amount", "digit_mode": "first_two"},
     "ACCOUNTS_PAYABLE", "FRAUD", 0.6, ["ap", "benford"],
     "First-two-digit Benford analysis on AP amounts"),
    ("AP14", "Invoice Just Below 10K Threshold", "threshold_avoidance",
     {"amount_field": "amount", "thresholds": [10000], "lower_band_pct": 0.9},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.2, ["ap", "threshold"],
     "Amounts in 9,000–9,999 band"),
    ("AP15", "Invoice Just Below 50K Threshold", "threshold_avoidance",
     {"amount_field": "amount", "thresholds": [50000], "lower_band_pct": 0.9},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.2, ["ap", "threshold"],
     "Amounts in 45,000–49,999 band"),
    ("AP16", "Invoice Just Below Multi-Level Approval", "threshold_avoidance",
     {"amount_field": "amount", "thresholds": [10000, 50000, 100000], "lower_band_pct": 0.9},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.3, ["ap", "threshold", "approval"],
     "Split-invoice / structuring across approval ladders"),
    ("AP17", "Vendor-Employee Name Match", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "vendor_name", "field_right": "employee_name", "method": "fuzzy", "threshold": 85}], "return": "matched"},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.4, ["ap", "conflict", "fraud"],
     "Vendor name fuzzy-matches an employee name"),
    ("AP18", "Vendor-Employee Bank Account Match", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "vendor_iban", "field_right": "employee_iban", "method": "exact"}], "return": "matched"},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.5, ["ap", "conflict", "fraud"],
     "Vendor IBAN exactly matches an employee IBAN"),
    ("AP19", "Vendor-Employee Address Match", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "vendor_address", "field_right": "employee_address", "method": "fuzzy", "threshold": 85}], "return": "matched"},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.3, ["ap", "conflict"],
     "Vendor address fuzzy-matches an employee address"),
    ("AP20", "Vendor-Employee Phone Match", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "vendor_phone", "field_right": "employee_phone", "method": "exact"}], "return": "matched"},
     "ACCOUNTS_PAYABLE", "FRAUD", 1.3, ["ap", "conflict"],
     "Vendor phone number exactly matches an employee phone"),
    ("AP21", "Vendor with PO Box Only", "keyword_scan",
     {"text_field": "vendor_address", "keywords": ["PO Box", "P.O. Box", "P O Box"], "case_sensitive": False},
     "ACCOUNTS_PAYABLE", "FRAUD", 0.7, ["ap", "vendor"],
     "Vendor master has only PO Box address"),
    ("AP22", "One-Time Vendors", "pattern_frequency",
     {"group_field": "vendor_id", "metric": "count", "threshold": 1, "threshold_direction": "below"},
     "ACCOUNTS_PAYABLE", "FRAUD", 0.6, ["ap", "vendor"],
     "Vendors with a single invoice only"),
    ("AP23", "Rare Vendor-GL Account Pairs", "rare_combination",
     {"field_a": "vendor_id", "field_b": "gl_account", "rarity_threshold_pct": 5.0},
     "ACCOUNTS_PAYABLE", "ANALYTICAL", 0.7, ["ap", "relational"],
     "Unusual vendor+GL account combinations"),
    ("AP24", "Amount Distribution Anomaly by Vendor", "amount_distribution_anomaly",
     {"amount_field": "amount", "grouping_field": "vendor_id", "method": "iqr", "threshold": 3.0},
     "ACCOUNTS_PAYABLE", "FRAUD", 0.8, ["ap", "outlier"],
     "Per-vendor amount outliers"),
    ("AP25", "Suspicious Keywords in Invoice Description", "keyword_scan",
     {"text_field": "description", "keywords": ["adjust", "reverse", "correction", "void", "test", "dummy"], "case_sensitive": False},
     "ACCOUNTS_PAYABLE", "FRAUD", 0.9, ["ap", "keyword"],
     "Flagged keywords in invoice description"),
]

AR = [
    ("AR01", "Duplicate Customer Invoice Numbers", "duplicates",
     {"key_fields": ["customer_id", "invoice_no"]}, "ACCOUNTS_RECEIVABLE", "FRAUD", 1.0,
     ["ar", "duplicate"], "Same invoice number under same customer"),
    ("AR02", "Credit Notes Without Original Invoice Reference", "referential_integrity",
     {"child_field": "ref_invoice_no", "parent_values": []},
     "ACCOUNTS_RECEIVABLE", "FRAUD", 1.1, ["ar", "credit"],
     "Credit note references an invoice that doesn't exist"),
    ("AR03", "AR Aging Analysis", "age",
     {"date_field": "due_date", "buckets": [[0, 30], [31, 60], [61, 90], [91, None]]},
     "ACCOUNTS_RECEIVABLE", "ANALYTICAL", 0.4, ["ar", "aging"],
     "Aging buckets on due_date"),
    ("AR04", "AR Aging Over 90 Days", "age",
     {"date_field": "due_date", "buckets": [[91, None]]},
     "ACCOUNTS_RECEIVABLE", "ANALYTICAL", 0.8, ["ar", "aging"],
     "Receivables aged beyond 90 days"),
    ("AR05", "Credit Limit Breaches", "range_validation",
     {"field": "balance", "compare_to_field": "credit_limit"},
     "ACCOUNTS_RECEIVABLE", "COMPLIANCE", 1.0, ["ar", "limit"],
     "Customer balance exceeding credit limit"),
    ("AR06", "Negative AR Balances", "range_validation",
     {"field": "balance", "max": 0},
     "ACCOUNTS_RECEIVABLE", "ANALYTICAL", 0.7, ["ar"],
     "Customers with credit balance"),
    ("AR07", "Round-Dollar Invoices", "round_number",
     {"amount_field": "invoice_amount", "round_pattern": "000"},
     "ACCOUNTS_RECEIVABLE", "FRAUD", 0.4, ["ar", "round"],
     "Invoices ending in 000"),
    ("AR08", "Benford on AR Invoice Amounts", "benford",
     {"numeric_field": "invoice_amount", "digit_mode": "first_two"},
     "ACCOUNTS_RECEIVABLE", "FRAUD", 0.6, ["ar", "benford"],
     "Benford first-two-digit on AR amounts"),
    ("AR09", "Customer Concentration Analysis", "classify",
     {"category_field": "customer_id", "subtotal_fields": ["invoice_amount"], "top_n": 10},
     "ACCOUNTS_RECEIVABLE", "ANALYTICAL", 0.3, ["ar", "concentration"],
     "Top-10 customers by revenue concentration"),
    ("AR10", "Unbilled Revenue", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "shipment_id", "field_right": "shipment_id", "method": "exact"}], "return": "unmatched_left"},
     "ACCOUNTS_RECEIVABLE", "FRAUD", 1.1, ["ar", "revenue"],
     "Shipments without a matching invoice"),
    ("AR11", "Fuzzy Duplicate Customer Names", "fuzzy_dup",
     {"field": "customer_name", "threshold": 85},
     "ACCOUNTS_RECEIVABLE", "ANALYTICAL", 0.7, ["ar", "customer"],
     "Near-duplicate customer master records"),
    ("AR12", "Amount Distribution Anomaly by Customer", "amount_distribution_anomaly",
     {"amount_field": "invoice_amount", "grouping_field": "customer_id", "method": "iqr", "threshold": 3.0},
     "ACCOUNTS_RECEIVABLE", "FRAUD", 0.8, ["ar", "outlier"],
     "Per-customer amount outliers"),
    ("AR13", "Large Write-Offs", "zscore_outlier",
     {"field": "writeoff_amount", "threshold": 3.0},
     "ACCOUNTS_RECEIVABLE", "FRAUD", 1.1, ["ar", "writeoff"],
     "Unusually large write-offs"),
    ("AR14", "Recurring Refunds Same Customer", "pattern_frequency",
     {"group_field": "customer_id", "metric": "count", "threshold": 3, "threshold_direction": "above", "filter_field": "type", "filter_value": "refund"},
     "ACCOUNTS_RECEIVABLE", "FRAUD", 1.0, ["ar", "refund"],
     "Customers with 3+ refunds"),
    ("AR15", "Invoice Date After Payment Date", "date_anomaly",
     {"date_field": "invoice_date", "check_type": "backdated", "compare_field": "payment_date"},
     "ACCOUNTS_RECEIVABLE", "FRAUD", 1.2, ["ar", "date"],
     "Invoice issued after payment received"),
]

GL = [
    ("GL01", "Duplicate Journal Entry IDs", "duplicates",
     {"key_fields": ["journal_id"]}, "GENERAL_LEDGER", "DATA_QUALITY", 1.0,
     ["gl", "duplicate"], "Journal IDs should be unique"),
    ("GL02", "Manual JE on Weekend", "weekend_transactions",
     {"date_field": "posting_date", "filter_field": "entry_type", "filter_value": "manual"},
     "GENERAL_LEDGER", "FRAUD", 1.2, ["gl", "manual", "temporal"],
     "Manual journal entries posted on Fri/Sat"),
    ("GL03", "Manual JE on Holiday", "weekend_transactions",
     {"date_field": "posting_date", "include_holidays": True, "holidays_ref": "uae",
      "filter_field": "entry_type", "filter_value": "manual"},
     "GENERAL_LEDGER", "FRAUD", 1.3, ["gl", "manual", "temporal"],
     "Manual journal entries on UAE holidays"),
    ("GL04", "JE After Business Hours", "after_hours",
     {"datetime_field": "posting_datetime", "business_start": "08:00", "business_end": "18:00"},
     "GENERAL_LEDGER", "FRAUD", 1.0, ["gl", "temporal"],
     "Journal entries posted outside business hours"),
    ("GL05", "JE Within 48 Hours of Period Close", "period_end_spike",
     {"date_field": "posting_date", "window_days": 2},
     "GENERAL_LEDGER", "FRAUD", 1.1, ["gl", "period"],
     "Activity spike within 48h of period close"),
    ("GL06", "JE Posted After Period Close", "date_anomaly",
     {"date_field": "posting_date", "check_type": "future", "compare_field": "period_close_date"},
     "GENERAL_LEDGER", "FRAUD", 1.4, ["gl", "period"],
     "Postings after period close date"),
    ("GL07", "Backdated JE", "date_anomaly",
     {"date_field": "posting_date", "check_type": "backdated", "compare_field": "entry_date"},
     "GENERAL_LEDGER", "FRAUD", 1.3, ["gl", "date"],
     "Posting date earlier than entry date"),
    ("GL08", "Management Override Detection", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "entered_by", "field_right": "executive_username", "method": "exact"}], "return": "matched"},
     "GENERAL_LEDGER", "FRAUD", 1.5, ["gl", "override"],
     "Manual entries by executive users"),
    ("GL09", "Rare GL Account Pairs", "rare_combination",
     {"field_a": "debit_account", "field_b": "credit_account", "rarity_threshold_pct": 3.0},
     "GENERAL_LEDGER", "ANALYTICAL", 0.8, ["gl", "accounts"],
     "Unusual debit/credit account combinations"),
    ("GL10", "Unbalanced Journal Entries", "range_validation",
     {"field": "balance_diff", "min": -0.01, "max": 0.01},
     "GENERAL_LEDGER", "DATA_QUALITY", 1.5, ["gl", "balance"],
     "Entries where debits ≠ credits"),
    ("GL11", "Benford on JE Debits", "benford",
     {"numeric_field": "debit_amount", "digit_mode": "first_two"},
     "GENERAL_LEDGER", "FRAUD", 0.6, ["gl", "benford"],
     "Benford analysis on debit amounts"),
    ("GL12", "Benford on JE Credits", "benford",
     {"numeric_field": "credit_amount", "digit_mode": "first_two"},
     "GENERAL_LEDGER", "FRAUD", 0.6, ["gl", "benford"],
     "Benford analysis on credit amounts"),
    ("GL13", "Round-Dollar Journal Entries", "round_number",
     {"amount_field": "amount", "round_pattern": "000"},
     "GENERAL_LEDGER", "FRAUD", 0.5, ["gl", "round"],
     "Amounts ending in 000"),
    ("GL14", "JE Without Description", "null_check",
     {"required_fields": ["description"]}, "GENERAL_LEDGER", "DATA_QUALITY", 0.6,
     ["gl", "quality"], "Missing narrative on journal entries"),
    ("GL15", "Suspicious Keywords in JE Description", "keyword_scan",
     {"text_field": "description", "keywords": ["plug", "test", "dummy", "reverse", "temp", "correction"], "case_sensitive": False},
     "GENERAL_LEDGER", "FRAUD", 1.0, ["gl", "keyword"],
     "Red-flag keywords in JE descriptions"),
    ("GL16", "Top N Users by Manual JE Value", "summarize",
     {"group_by_fields": ["entered_by"], "subtotal_fields": ["amount"], "top_n": 10,
      "filter_field": "entry_type", "filter_value": "manual"},
     "GENERAL_LEDGER", "ANALYTICAL", 0.3, ["gl", "users"],
     "Top users by manual JE value"),
    ("GL17", "JE Amount Outliers (z-score)", "zscore_outlier",
     {"field": "amount", "threshold": 3.0},
     "GENERAL_LEDGER", "FRAUD", 0.8, ["gl", "outlier"],
     "JE amounts with z-score > 3"),
    ("GL18", "JE Amount Outliers (isolation forest)", "isolation_forest",
     {"feature_fields": ["amount"], "contamination": 0.02},
     "GENERAL_LEDGER", "FRAUD", 0.9, ["gl", "ml"],
     "Multivariate JE anomaly detection"),
    ("GL19", "Reversing Entries Without Original", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "reverses_journal_id", "field_right": "journal_id", "method": "exact"}], "return": "unmatched_left"},
     "GENERAL_LEDGER", "FRAUD", 1.2, ["gl", "reversal"],
     "Reversing entries without matching original"),
    ("GL20", "Account Activity Spike", "trend_deviation",
     {"numeric_field": "amount", "date_field": "posting_date", "grouping_field": "gl_account", "residual_threshold": 2.5},
     "GENERAL_LEDGER", "ANALYTICAL", 0.7, ["gl", "trend"],
     "Unusual activity on specific accounts"),
]

PR = [
    ("PR01", "Duplicate Payroll Entries (employee + period)", "duplicates",
     {"key_fields": ["employee_id", "pay_period"]}, "PAYROLL", "FRAUD", 1.3,
     ["pr", "duplicate"], "Employee paid twice in same period"),
    ("PR02", "Ghost Employees (no HR record)", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "employee_id", "field_right": "employee_id", "method": "exact"}], "return": "unmatched_left"},
     "PAYROLL", "FRAUD", 1.5, ["pr", "ghost"],
     "Payroll records without matching HR master record"),
    ("PR03", "Terminated Employees Still Paid", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "employee_id", "field_right": "employee_id", "method": "exact"}], "return": "matched"},
     "PAYROLL", "FRAUD", 1.4, ["pr", "termination"],
     "Payroll date after HR termination date"),
    ("PR04", "Shared Bank Accounts Across Employees", "duplicates",
     {"key_fields": ["bank_account"]}, "PAYROLL", "FRAUD", 1.2,
     ["pr", "bank"], "Multiple employees sharing bank account"),
    ("PR05", "Shared Home Address Across Employees", "fuzzy_dup",
     {"field": "address", "threshold": 90}, "PAYROLL", "ANALYTICAL", 0.7,
     ["pr", "address"], "Employees sharing home address"),
    ("PR06", "Fuzzy Duplicate Employee Names", "fuzzy_dup",
     {"field": "full_name", "threshold": 85}, "PAYROLL", "ANALYTICAL", 0.7,
     ["pr", "duplicate"], "Near-duplicate employee names"),
    ("PR07", "Overtime Hours Outliers", "zscore_outlier",
     {"field": "overtime_hours", "threshold": 3.0}, "PAYROLL", "FRAUD", 0.8,
     ["pr", "overtime"], "Abnormal overtime claims"),
    ("PR08", "Bonus-to-Base Ratio Anomaly", "amount_distribution_anomaly",
     {"amount_field": "bonus_ratio", "grouping_field": "grade", "method": "iqr", "threshold": 3.0},
     "PAYROLL", "FRAUD", 1.0, ["pr", "bonus"],
     "Bonus ratio outliers within grade"),
    ("PR09", "Payroll Posted on Weekend", "weekend_transactions",
     {"date_field": "posting_date"}, "PAYROLL", "FRAUD", 0.9,
     ["pr", "temporal"], "Payroll posted on Fri/Sat"),
    ("PR10", "Round-Dollar Bonuses", "round_number",
     {"amount_field": "bonus_amount", "round_pattern": "000"},
     "PAYROLL", "FRAUD", 0.4, ["pr", "bonus"],
     "Bonuses ending in 000"),
    ("PR11", "Pay Rate Increase Outliers", "zscore_outlier",
     {"field": "pay_rate_change_pct", "threshold": 3.0},
     "PAYROLL", "FRAUD", 1.0, ["pr", "rate"],
     "Unusually large pay rate increases"),
    ("PR12", "Duplicate Tax IDs Across Employees", "duplicates",
     {"key_fields": ["emirates_id"]}, "PAYROLL", "FRAUD", 1.4,
     ["pr", "tax"], "Same Emirates ID used for multiple employees"),
    ("PR13", "Employees with Sequential IDs & Same Hire Date", "pattern_frequency",
     {"group_field": "hire_date", "metric": "count", "threshold": 5, "threshold_direction": "above"},
     "PAYROLL", "FRAUD", 0.9, ["pr", "ghost"],
     "Mass hires on a single date"),
    ("PR14", "Reactivated Terminated Employees", "pattern_frequency",
     {"group_field": "employee_id", "metric": "count", "threshold": 2, "threshold_direction": "above",
      "filter_field": "status_change", "filter_value": "reactivation"},
     "PAYROLL", "FRAUD", 1.1, ["pr", "status"],
     "Employees reactivated more than once"),
    ("PR15", "Benford on Gross Pay", "benford",
     {"numeric_field": "gross_pay", "digit_mode": "first_two"},
     "PAYROLL", "FRAUD", 0.6, ["pr", "benford"],
     "Benford analysis on gross pay"),
]

FA = [
    ("FA01", "Duplicate Asset IDs", "duplicates",
     {"key_fields": ["asset_id"]}, "FIXED_ASSETS", "DATA_QUALITY", 1.0,
     ["fa", "duplicate"], "Asset IDs should be unique"),
    ("FA02", "Assets with Negative NBV", "range_validation",
     {"field": "nbv", "max": 0}, "FIXED_ASSETS", "DATA_QUALITY", 1.1,
     ["fa", "nbv"], "Net book value below zero"),
    ("FA03", "Fully Depreciated but Not Disposed", "range_validation",
     {"field": "nbv", "min": -0.01, "max": 0.01}, "FIXED_ASSETS", "ANALYTICAL", 0.7,
     ["fa", "depreciation"], "NBV=0 yet asset still active"),
    ("FA04", "Asset Cost Outliers", "zscore_outlier",
     {"field": "acquisition_cost", "threshold": 3.0}, "FIXED_ASSETS", "FRAUD", 0.8,
     ["fa", "cost"], "Unusual acquisition costs"),
    ("FA05", "Depreciation Method Changes", "pattern_frequency",
     {"group_field": "asset_id", "metric": "count", "threshold": 1, "threshold_direction": "above",
      "filter_field": "change_type", "filter_value": "depreciation_method"},
     "FIXED_ASSETS", "FRAUD", 0.9, ["fa", "depreciation"],
     "Assets with depreciation method changes"),
    ("FA06", "Additions Without Approval", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "addition_id", "field_right": "approval_id", "method": "exact"}], "return": "unmatched_left"},
     "FIXED_ASSETS", "COMPLIANCE", 1.2, ["fa", "approval"],
     "Fixed asset additions without documented approval"),
    ("FA07", "Unusual Disposal Gains", "zscore_outlier",
     {"field": "disposal_gain", "threshold": 3.0}, "FIXED_ASSETS", "FRAUD", 1.0,
     ["fa", "disposal"], "Abnormal gain on asset disposal"),
    ("FA08", "Ghost Assets (no physical verification)", "cross_match",
     {"right_dataset": [], "match_rules": [{"field_left": "asset_id", "field_right": "asset_id", "method": "exact"}], "return": "unmatched_left"},
     "FIXED_ASSETS", "FRAUD", 1.3, ["fa", "ghost"],
     "Assets in register but missing from last physical count"),
    ("FA09", "Benford on Asset Costs", "benford",
     {"numeric_field": "acquisition_cost", "digit_mode": "first_two"},
     "FIXED_ASSETS", "FRAUD", 0.6, ["fa", "benford"],
     "Benford analysis on acquisition costs"),
    ("FA10", "Asset Transfers Between Subsidiaries", "pattern_frequency",
     {"group_field": "asset_id", "metric": "count", "threshold": 2, "threshold_direction": "above",
      "filter_field": "transfer_type", "filter_value": "subsidiary"},
     "FIXED_ASSETS", "ANALYTICAL", 0.8, ["fa", "transfer"],
     "Assets transferred multiple times between subsidiaries"),
]

TEMPLATES: list[tuple] = [*UNIVERSAL, *AP, *AR, *GL, *PR, *FA]



